services:
    simple_mongo:
        class: RedpillLinpro\NosqlBundle\Services\SimpleMongo
        arguments:
            dbhost: %simple_mongo.dbhost%
            dbname: %simple_mongo.dbname%
            dbuser: %simple_mongo.dbuser%
            dbpass: %simple_mongo.dbpass%

    arrayexample_manager:
        class: RedpillLinpro\ExamplesBundle\Manager\ArrayExample
        arguments: [ @simple_mongo ]

